# Generated by scripts/generate_categories.py. DO NOT EDIT MANUALLY.
# flake8: noqa
# pylint: disable=all
from typing import Dict, Literal, Union

# --- Numerical Category IDs (Generated) ---
AUDIO_MUSIC = 101
AUDIO_AUDIO_BOOKS = 102
AUDIO_SOUND_CLIPS = 103
AUDIO_FLAC = 104
AUDIO_OTHER = 199
VIDEO_MOVIES = 201
VIDEO_MOVIES_DVDR = 202
VIDEO_MUSIC_VIDEOS = 203
VIDEO_MOVIE_CLIPS = 204
VIDEO_TV_SHOWS = 205
VIDEO_HANDHELD = 206
VIDEO_HD___MOVIES = 207
VIDEO_HD___TV_SHOWS = 208
VIDEO_THREE_D = 209
VIDEO_CAM_TS = 210
VIDEO_UHD_4K___MOVIES = 211
VIDEO_UHD_4K___TV_SHOWS = 212
VIDEO_OTHER = 299
APPLICATION_WINDOWS = 301
APPLICATION_MAC = 302
APPLICATION_UNIX = 303
APPLICATION_HANDHELD = 304
APPLICATION_IOS = 305
APPLICATION_ANDROID = 306
APPLICATION_OTHER_OS = 399
GAMES_PC = 401
GAMES_MAC = 402
GAMES_PSX = 403
GAMES_XBOX360 = 404
GAMES_WII = 405
GAMES_HANDHELD = 406
GAMES_IOS = 407
GAMES_ANDROID = 408
GAMES_OTHER = 499
PORN_MOVIES = 501
PORN_MOVIES_DVDR = 502
PORN_PICTURES = 503
PORN_GAMES = 504
PORN_HD___MOVIES = 505
PORN_MOVIE_CLIPS = 506
PORN_UHD_4K___MOVIES = 507
PORN_OTHER = 599
OTHER_E_BOOKS = 601
OTHER_COMICS = 602
OTHER_PICTURES = 603
OTHER_COVERS = 604
OTHER_PHYSIBLES = 605
OTHER_OTHER = 699

# --- CategoryId Type (Generated) ---
CategoryId = Literal[
    101, 102, 103, 104, 199,
    201, 202, 203, 204, 205,
    206, 207, 208, 209, 210,
    211, 212, 299, 301, 302,
    303, 304, 305, 306, 399,
    401, 402, 403, 404, 405,
    406, 407, 408, 499, 501,
    502, 503, 504, 505, 506,
    507, 599, 601, 602, 603,
    604, 605, 699
]

# --- Top100Category Type (Manual Definition) ---
Top100Category = Union[CategoryId, Literal["all", "recent"]]

# --- CATEGORIES Dictionary (Generated) ---
CATEGORIES: Dict[str, Dict[str, CategoryId]] = {
    "application": {
        "windows": 301,
        "mac": 302,
        "unix": 303,
        "handheld": 304,
        "ios": 305,
        "android": 306,
        "other_os": 399,
    },
    "audio": {
        "music": 101,
        "audio_books": 102,
        "sound_clips": 103,
        "flac": 104,
        "other": 199,
    },
    "games": {
        "pc": 401,
        "mac": 402,
        "psx": 403,
        "xbox360": 404,
        "wii": 405,
        "handheld": 406,
        "ios": 407,
        "android": 408,
        "other": 499,
    },
    "other": {
        "e_books": 601,
        "comics": 602,
        "pictures": 603,
        "covers": 604,
        "physibles": 605,
        "other": 699,
    },
    "porn": {
        "movies": 501,
        "movies_dvdr": 502,
        "pictures": 503,
        "games": 504,
        "hd___movies": 505,
        "movie_clips": 506,
        "uhd_4k___movies": 507,
        "other": 599,
    },
    "video": {
        "movies": 201,
        "movies_dvdr": 202,
        "music_videos": 203,
        "movie_clips": 204,
        "tv_shows": 205,
        "handheld": 206,
        "hd___movies": 207,
        "hd___tv_shows": 208,
        "three_d": 209,
        "cam_ts": 210,
        "uhd_4k___movies": 211,
        "uhd_4k___tv_shows": 212,
        "other": 299,
    },
}

# --- Default Base URL and User Agent (Manual Definition) ---
DEFAULT_BASE_URL = "https://apibay.org"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
